import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AuthProvider } from "./Provider";
import { getServerSession } from "next-auth";
import { options } from "./api/auth/[...nextauth]/options";
import { redirect } from "next/navigation";
import Navbar from "@/components/Dashboard/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(options);
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          {session ? (
            <main className="flex flex-col h-screen w-screen bg-[#000505]">
              <Navbar />
              {children}
            </main>
          ) : (
            redirect("/login")
          )}
        </AuthProvider>
      </body>
    </html>
  );
}
